### ISSUE TITLE
TV control not working

### ISSUE THREAD

**Issue by Gdanycz** [popeen/Home-Assistant-Custom-Component-TCL-Remote#6]
Hi, I tried the integration to change the source on the tv, but it pops up the message "Unknown error" and in the log I see:

Logger: homeassistant.components.websocket_api.http.connection
Zdroj: custom_components/tcl_tv_remote/__init__.py:26
integrace: Home Assistant WebSocket API (dokumentace, problémy)
První výskyt: 12:06:51 (2 výskyty)
Naposledy logováno: 12:07:52

[547674158512] Error handling message: Unknown error (unknown_error) Gdany from 46.174.56.5 (Mozilla/5.0 (Linux; Android 13; 2201117SY Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/127.0.6533.103 Mobile Safari/537.36 Home Assistant/2024.7.3-13278 (Android 13; 2201117SY))
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 793, in handle_execute_script
    script_result = await script_obj.async_run(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1799, in async_run
    return await asyncio.shield(create_eager_task(run.async_run()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 463, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 527, in _async_step
    self._handle_exception(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 557, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 525, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 764, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 727, in _async_run_long_action
    return await long_task
           ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2763, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2813, in _execute_service
    return await self._hass.async_add_executor_job(target, service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tcl_tv_remote/__init__.py", line 26, in send_key
    tv.keypress(call.data.get(ATTR_KEY));
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tcltvremote/tcltvremote.py", line 13, in keypress
    client_socket.connect((self.ip, self.port))
ConnectionRefusedError: [Errno 111] Connection refused

**Comment by zpljd258** [comment]
same issue

**Comment by wambs** [comment]
same issue, tried a couple of different ports, 4123, 8123, 1925, I'm sure IP addr is correct
